ITEMS=dir type hwphp
VYPACK=..\vypack.exe
RM=del /q

ALL=$(patsubst %,%.run,$(ITEMS))

test: $(ALL)

clean:
	$(RM) *.exe

.exe.run:
	$<

dir.exe: $(VYPACK)
	$(VYPACK) -o $@ -c cmd.exe -a /c -a dir

type.exe: $(VYPACK) x.txt
	$(VYPACK) -o $@ -c cmd.exe -a /c -a type -a %vypack%\x.txt -f x.txt
	
hwphp.exe: $(VYPACK) hw.php
	$(VYPACK) -o $@ -x php.exe -a hw.php -f hw.php

.PHONY: %.run

.PRECIOUS: %.exe

.SUFFIXES: .exe .run